# 由 gen_vendor_mk.py 依据本机 stock system.img 提取的 blobs 生成。
# 只包含 vendor/ 下的真实二进制与固件；构建脚本(Android.mk 等)不在此列。
#
# 与上游 Cubot X18 vendor 树的关键差异：
#   - 本机 HAL 命名为 *.mt6737t.so（对应 ro.board.platform=mt6737t），
#     而非 X18 的 *.mt6735t.so —— 名字对不上会导致 HAL 加载失败、开机循环
#   - 含本机专有的 C2K 基带固件 modem_3_3g_n.img 与 libc2kril.so

PRODUCT_COPY_FILES += \
    vendor/CUBOT/X18/vendor/bin/MtkCodecService:system/vendor/bin/MtkCodecService \
    vendor/CUBOT/X18/vendor/bin/aal:system/vendor/bin/aal \
    vendor/CUBOT/X18/vendor/bin/aee:system/vendor/bin/aee \
    vendor/CUBOT/X18/vendor/bin/aee_archive:system/vendor/bin/aee_archive \
    vendor/CUBOT/X18/vendor/bin/aee_core_forwarder:system/vendor/bin/aee_core_forwarder \
    vendor/CUBOT/X18/vendor/bin/aee_dumpstate:system/vendor/bin/aee_dumpstate \
    vendor/CUBOT/X18/vendor/bin/afx133d:system/vendor/bin/afx133d \
    vendor/CUBOT/X18/vendor/bin/akmd09911:system/vendor/bin/akmd09911 \
    vendor/CUBOT/X18/vendor/bin/akmd8963:system/vendor/bin/akmd8963 \
    vendor/CUBOT/X18/vendor/bin/akmd8975:system/vendor/bin/akmd8975 \
    vendor/CUBOT/X18/vendor/bin/ami304d:system/vendor/bin/ami304d \
    vendor/CUBOT/X18/vendor/bin/atci_service:system/vendor/bin/atci_service \
    vendor/CUBOT/X18/vendor/bin/atcid:system/vendor/bin/atcid \
    vendor/CUBOT/X18/vendor/bin/audiocmdservice_atci:system/vendor/bin/audiocmdservice_atci \
    vendor/CUBOT/X18/vendor/bin/autobt:system/vendor/bin/autobt \
    vendor/CUBOT/X18/vendor/bin/autokd:system/vendor/bin/autokd \
    vendor/CUBOT/X18/vendor/bin/batterywarning:system/vendor/bin/batterywarning \
    vendor/CUBOT/X18/vendor/bin/bmm050d:system/vendor/bin/bmm050d \
    vendor/CUBOT/X18/vendor/bin/boot_logo_updater:system/vendor/bin/boot_logo_updater \
    vendor/CUBOT/X18/vendor/bin/bypass:system/vendor/bin/bypass \
    vendor/CUBOT/X18/vendor/bin/ccci_fsd:system/vendor/bin/ccci_fsd \
    vendor/CUBOT/X18/vendor/bin/ccci_mdinit:system/vendor/bin/ccci_mdinit \
    vendor/CUBOT/X18/vendor/bin/charon:system/vendor/bin/charon \
    vendor/CUBOT/X18/vendor/bin/cmddumper:system/vendor/bin/cmddumper \
    vendor/CUBOT/X18/vendor/bin/dhcp6c:system/vendor/bin/dhcp6c \
    vendor/CUBOT/X18/vendor/bin/dhcp6ctl:system/vendor/bin/dhcp6ctl \
    vendor/CUBOT/X18/vendor/bin/dhcp6s:system/vendor/bin/dhcp6s \
    vendor/CUBOT/X18/vendor/bin/dm_agent_binder:system/vendor/bin/dm_agent_binder \
    vendor/CUBOT/X18/vendor/bin/dmlog:system/vendor/bin/dmlog \
    vendor/CUBOT/X18/vendor/bin/downloader:system/vendor/bin/downloader \
    vendor/CUBOT/X18/vendor/bin/emdlogger1:system/vendor/bin/emdlogger1 \
    vendor/CUBOT/X18/vendor/bin/emdlogger2:system/vendor/bin/emdlogger2 \
    vendor/CUBOT/X18/vendor/bin/emdlogger3:system/vendor/bin/emdlogger3 \
    vendor/CUBOT/X18/vendor/bin/emdlogger5:system/vendor/bin/emdlogger5 \
    vendor/CUBOT/X18/vendor/bin/epdg_wod:system/vendor/bin/epdg_wod \
    vendor/CUBOT/X18/vendor/bin/factory:system/vendor/bin/factory \
    vendor/CUBOT/X18/vendor/bin/flashlessd:system/vendor/bin/flashlessd \
    vendor/CUBOT/X18/vendor/bin/fsck_msdos_mtk:system/vendor/bin/fsck_msdos_mtk \
    vendor/CUBOT/X18/vendor/bin/fuelgauged:system/vendor/bin/fuelgauged \
    vendor/CUBOT/X18/vendor/bin/ged_srv:system/vendor/bin/ged_srv \
    vendor/CUBOT/X18/vendor/bin/geomagneticd:system/vendor/bin/geomagneticd \
    vendor/CUBOT/X18/vendor/bin/gsm0710muxd:system/vendor/bin/gsm0710muxd \
    vendor/CUBOT/X18/vendor/bin/gsm0710muxdmd2:system/vendor/bin/gsm0710muxdmd2 \
    vendor/CUBOT/X18/vendor/bin/init_thh:system/vendor/bin/init_thh \
    vendor/CUBOT/X18/vendor/bin/ipsec:system/vendor/bin/ipsec \
    vendor/CUBOT/X18/vendor/bin/ipsec_mon:system/vendor/bin/ipsec_mon \
    vendor/CUBOT/X18/vendor/bin/kpoc_charger:system/vendor/bin/kpoc_charger \
    vendor/CUBOT/X18/vendor/bin/lcdc_screen_cap:system/vendor/bin/lcdc_screen_cap \
    vendor/CUBOT/X18/vendor/bin/lsm303md:system/vendor/bin/lsm303md \
    vendor/CUBOT/X18/vendor/bin/magd:system/vendor/bin/magd \
    vendor/CUBOT/X18/vendor/bin/matv:system/vendor/bin/matv \
    vendor/CUBOT/X18/vendor/bin/mc6420d:system/vendor/bin/mc6420d \
    vendor/CUBOT/X18/vendor/bin/md_ctrl:system/vendor/bin/md_ctrl \
    vendor/CUBOT/X18/vendor/bin/mdlogger:system/vendor/bin/mdlogger \
    vendor/CUBOT/X18/vendor/bin/memorydumper:system/vendor/bin/memorydumper \
    vendor/CUBOT/X18/vendor/bin/memsicd:system/vendor/bin/memsicd \
    vendor/CUBOT/X18/vendor/bin/memsicd3416x:system/vendor/bin/memsicd3416x \
    vendor/CUBOT/X18/vendor/bin/meta_tst:system/vendor/bin/meta_tst \
    vendor/CUBOT/X18/vendor/bin/mnld:system/vendor/bin/mnld \
    vendor/CUBOT/X18/vendor/bin/mobile_log_d:system/vendor/bin/mobile_log_d \
    vendor/CUBOT/X18/vendor/bin/msensord:system/vendor/bin/msensord \
    vendor/CUBOT/X18/vendor/bin/mtk_agpsd:system/vendor/bin/mtk_agpsd \
    vendor/CUBOT/X18/vendor/bin/mtkmal:system/vendor/bin/mtkmal \
    vendor/CUBOT/X18/vendor/bin/mtkrild:system/vendor/bin/mtkrild \
    vendor/CUBOT/X18/vendor/bin/mtkrildmd2:system/vendor/bin/mtkrildmd2 \
    vendor/CUBOT/X18/vendor/bin/muxreport:system/vendor/bin/muxreport \
    vendor/CUBOT/X18/vendor/bin/netdiag:system/vendor/bin/netdiag \
    vendor/CUBOT/X18/vendor/bin/nvram_agent_binder:system/vendor/bin/nvram_agent_binder \
    vendor/CUBOT/X18/vendor/bin/nvram_daemon:system/vendor/bin/nvram_daemon \
    vendor/CUBOT/X18/vendor/bin/orientationd:system/vendor/bin/orientationd \
    vendor/CUBOT/X18/vendor/bin/perf_native_test:system/vendor/bin/perf_native_test \
    vendor/CUBOT/X18/vendor/bin/pq:system/vendor/bin/pq \
    vendor/CUBOT/X18/vendor/bin/program_binary_builder:system/vendor/bin/program_binary_builder \
    vendor/CUBOT/X18/vendor/bin/program_binary_service:system/vendor/bin/program_binary_service \
    vendor/CUBOT/X18/vendor/bin/qmcX983d:system/vendor/bin/qmcX983d \
    vendor/CUBOT/X18/vendor/bin/radvd:system/vendor/bin/radvd \
    vendor/CUBOT/X18/vendor/bin/resize_ext4:system/vendor/bin/resize_ext4 \
    vendor/CUBOT/X18/vendor/bin/rilproxy:system/vendor/bin/rilproxy \
    vendor/CUBOT/X18/vendor/bin/rs2spir:system/vendor/bin/rs2spir \
    vendor/CUBOT/X18/vendor/bin/rtt:system/vendor/bin/rtt \
    vendor/CUBOT/X18/vendor/bin/s62xd:system/vendor/bin/s62xd \
    vendor/CUBOT/X18/vendor/bin/slpd:system/vendor/bin/slpd \
    vendor/CUBOT/X18/vendor/bin/sn:system/vendor/bin/sn \
    vendor/CUBOT/X18/vendor/bin/spir2cl:system/vendor/bin/spir2cl \
    vendor/CUBOT/X18/vendor/bin/spm_loader:system/vendor/bin/spm_loader \
    vendor/CUBOT/X18/vendor/bin/st350:system/vendor/bin/st350 \
    vendor/CUBOT/X18/vendor/bin/st480d:system/vendor/bin/st480d \
    vendor/CUBOT/X18/vendor/bin/starter:system/vendor/bin/starter \
    vendor/CUBOT/X18/vendor/bin/statusd:system/vendor/bin/statusd \
    vendor/CUBOT/X18/vendor/bin/stp_dump3:system/vendor/bin/stp_dump3 \
    vendor/CUBOT/X18/vendor/bin/stroke:system/vendor/bin/stroke \
    vendor/CUBOT/X18/vendor/bin/superumount:system/vendor/bin/superumount \
    vendor/CUBOT/X18/vendor/bin/sysenv_daemon:system/vendor/bin/sysenv_daemon \
    vendor/CUBOT/X18/vendor/bin/teei_daemon:system/vendor/bin/teei_daemon \
    vendor/CUBOT/X18/vendor/bin/terservice:system/vendor/bin/terservice \
    vendor/CUBOT/X18/vendor/bin/tertestclient:system/vendor/bin/tertestclient \
    vendor/CUBOT/X18/vendor/bin/thermal:system/vendor/bin/thermal \
    vendor/CUBOT/X18/vendor/bin/thermal_manager:system/vendor/bin/thermal_manager \
    vendor/CUBOT/X18/vendor/bin/thermald:system/vendor/bin/thermald \
    vendor/CUBOT/X18/vendor/bin/thermalindicator:system/vendor/bin/thermalindicator \
    vendor/CUBOT/X18/vendor/bin/tiny_mkswap:system/vendor/bin/tiny_mkswap \
    vendor/CUBOT/X18/vendor/bin/tiny_swapoff:system/vendor/bin/tiny_swapoff \
    vendor/CUBOT/X18/vendor/bin/tiny_swapon:system/vendor/bin/tiny_swapon \
    vendor/CUBOT/X18/vendor/bin/viaradiooptions:system/vendor/bin/viaradiooptions \
    vendor/CUBOT/X18/vendor/bin/viarild:system/vendor/bin/viarild \
    vendor/CUBOT/X18/vendor/bin/volte_imcb:system/vendor/bin/volte_imcb \
    vendor/CUBOT/X18/vendor/bin/volte_stack:system/vendor/bin/volte_stack \
    vendor/CUBOT/X18/vendor/bin/volte_ua:system/vendor/bin/volte_ua \
    vendor/CUBOT/X18/vendor/bin/vtservice:system/vendor/bin/vtservice \
    vendor/CUBOT/X18/vendor/bin/wfca:system/vendor/bin/wfca \
    vendor/CUBOT/X18/vendor/bin/wifi2agps:system/vendor/bin/wifi2agps \
    vendor/CUBOT/X18/vendor/bin/wmt_concurrency:system/vendor/bin/wmt_concurrency \
    vendor/CUBOT/X18/vendor/bin/wmt_launcher:system/vendor/bin/wmt_launcher \
    vendor/CUBOT/X18/vendor/bin/wmt_loader:system/vendor/bin/wmt_loader \
    vendor/CUBOT/X18/vendor/bin/wmt_loopback:system/vendor/bin/wmt_loopback \
    vendor/CUBOT/X18/vendor/etc/.tp/.ht120.mtc:system/vendor/etc/.tp/.ht120.mtc \
    vendor/CUBOT/X18/vendor/etc/.tp/thermal.conf:system/vendor/etc/.tp/thermal.conf \
    vendor/CUBOT/X18/vendor/etc/.tp/thermal.off.conf:system/vendor/etc/.tp/thermal.off.conf \
    vendor/CUBOT/X18/vendor/etc/aee-config:system/vendor/etc/aee-config \
    vendor/CUBOT/X18/vendor/etc/agps_profiles_conf2.xml:system/vendor/etc/agps_profiles_conf2.xml \
    vendor/CUBOT/X18/vendor/etc/appwidget/3dwidgets.xml:system/vendor/etc/appwidget/3dwidgets.xml \
    vendor/CUBOT/X18/vendor/etc/audio_device.xml:system/vendor/etc/audio_device.xml \
    vendor/CUBOT/X18/vendor/etc/audio_em.xml:system/vendor/etc/audio_em.xml \
    vendor/CUBOT/X18/vendor/etc/audio_param/AudioParamOptions.xml:system/vendor/etc/audio_param/AudioParamOptions.xml \
    vendor/CUBOT/X18/vendor/etc/audio_policy.conf:system/vendor/etc/audio_policy.conf \
    vendor/CUBOT/X18/vendor/etc/cdma_ecc_list.xml:system/vendor/etc/cdma_ecc_list.xml \
    vendor/CUBOT/X18/vendor/etc/cdma_ecc_list_ss.xml:system/vendor/etc/cdma_ecc_list_ss.xml \
    vendor/CUBOT/X18/vendor/etc/custom.conf:system/vendor/etc/custom.conf \
    vendor/CUBOT/X18/vendor/etc/disableapplist.txt:system/vendor/etc/disableapplist.txt \
    vendor/CUBOT/X18/vendor/etc/ecc_list.xml:system/vendor/etc/ecc_list.xml \
    vendor/CUBOT/X18/vendor/etc/emdlogger_usb_config.prop:system/vendor/etc/emdlogger_usb_config.prop \
    vendor/CUBOT/X18/vendor/etc/factory.ini:system/vendor/etc/factory.ini \
    vendor/CUBOT/X18/vendor/etc/init/init.mal.rc:system/vendor/etc/init/init.mal.rc \
    vendor/CUBOT/X18/vendor/etc/init/init.wod.rc:system/vendor/etc/init/init.wod.rc \
    vendor/CUBOT/X18/vendor/etc/ipsec/ipsec.conf:system/vendor/etc/ipsec/ipsec.conf \
    vendor/CUBOT/X18/vendor/etc/ipsec/ipsec.d/cacerts/Entrust.net_Certification_Authority_2048.cer:system/vendor/etc/ipsec/ipsec.d/cacerts/Entrust.net_Certification_Authority_2048.cer \
    vendor/CUBOT/X18/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_PCA_G3_Root.der:system/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_PCA_G3_Root.der \
    vendor/CUBOT/X18/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA.der:system/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA.der \
    vendor/CUBOT/X18/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA_G2_ECC.der:system/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA_G2_ECC.der \
    vendor/CUBOT/X18/vendor/etc/ipsec/ipsec.d/cacerts/Root_CA_1003.crt:system/vendor/etc/ipsec/ipsec.d/cacerts/Root_CA_1003.crt \
    vendor/CUBOT/X18/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G4.der:system/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G4.der \
    vendor/CUBOT/X18/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G5.der:system/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G5.der \
    vendor/CUBOT/X18/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignUniversalRootCertification.der:system/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignUniversalRootCertification.der \
    vendor/CUBOT/X18/vendor/etc/ipsec/ipsec.d/cacerts/thawte.der:system/vendor/etc/ipsec/ipsec.d/cacerts/thawte.der \
    vendor/CUBOT/X18/vendor/etc/ipsec/ssl/openssl.cnf:system/vendor/etc/ipsec/ssl/openssl.cnf \
    vendor/CUBOT/X18/vendor/etc/ipsec/strongswan.conf:system/vendor/etc/ipsec/strongswan.conf \
    vendor/CUBOT/X18/vendor/etc/ipsec/updown_script:system/vendor/etc/ipsec/updown_script \
    vendor/CUBOT/X18/vendor/etc/ipsec/wod_cust.conf:system/vendor/etc/ipsec/wod_cust.conf \
    vendor/CUBOT/X18/vendor/etc/ipsec/wod_optr.conf:system/vendor/etc/ipsec/wod_optr.conf \
    vendor/CUBOT/X18/vendor/etc/mddb/BPLGUInfoCustomAppSrcP_MT6735_S00_MOLY_LR9_W1444_MD_LWTG_MP_V110_5_P12_1_ltg_n:system/vendor/etc/mddb/BPLGUInfoCustomAppSrcP_MT6735_S00_MOLY_LR9_W1444_MD_LWTG_MP_V110_5_P12_1_ltg_n \
    vendor/CUBOT/X18/vendor/etc/mddb/BPLGUInfoCustomAppSrcP_MT6735_S00_MOLY_LR9_W1444_MD_LWTG_MP_V110_5_P12_1_lwg_n:system/vendor/etc/mddb/BPLGUInfoCustomAppSrcP_MT6735_S00_MOLY_LR9_W1444_MD_LWTG_MP_V110_5_P12_1_lwg_n \
    vendor/CUBOT/X18/vendor/etc/mddb/BPMdMetaDatabase_MOLY_LR9_W1444_MD_LWTG_MP_V110_5_P12_1_ltg_n:system/vendor/etc/mddb/BPMdMetaDatabase_MOLY_LR9_W1444_MD_LWTG_MP_V110_5_P12_1_ltg_n \
    vendor/CUBOT/X18/vendor/etc/mddb/BPMdMetaDatabase_MOLY_LR9_W1444_MD_LWTG_MP_V110_5_P12_1_lwg_n:system/vendor/etc/mddb/BPMdMetaDatabase_MOLY_LR9_W1444_MD_LWTG_MP_V110_5_P12_1_lwg_n \
    vendor/CUBOT/X18/vendor/etc/mddb/DbgInfo_LR9.W1444.MD.LWTG.MP_BD6737M_65_A_N_MOLY_LR9_W1444_MD_LWTG_MP_V110_5_P12_2019_01_15_14_37_1_ltg_n:system/vendor/etc/mddb/DbgInfo_LR9.W1444.MD.LWTG.MP_BD6737M_65_A_N_MOLY_LR9_W1444_MD_LWTG_MP_V110_5_P12_2019_01_15_14_37_1_ltg_n \
    vendor/CUBOT/X18/vendor/etc/mddb/DbgInfo_LR9.W1444.MD.LWTG.MP_BD6737M_65_A_N_MOLY_LR9_W1444_MD_LWTG_MP_V110_5_P12_2019_01_15_14_38_1_lwg_n:system/vendor/etc/mddb/DbgInfo_LR9.W1444.MD.LWTG.MP_BD6737M_65_A_N_MOLY_LR9_W1444_MD_LWTG_MP_V110_5_P12_2019_01_15_14_38_1_lwg_n \
    vendor/CUBOT/X18/vendor/etc/mddb/mdm_layout_desc_1_ltg_n.dat:system/vendor/etc/mddb/mdm_layout_desc_1_ltg_n.dat \
    vendor/CUBOT/X18/vendor/etc/mddb/mdm_layout_desc_1_lwg_n.dat:system/vendor/etc/mddb/mdm_layout_desc_1_lwg_n.dat \
    vendor/CUBOT/X18/vendor/etc/mtk_omx_core.cfg:system/vendor/etc/mtk_omx_core.cfg \
    vendor/CUBOT/X18/vendor/etc/mtklog-config.prop:system/vendor/etc/mtklog-config.prop \
    vendor/CUBOT/X18/vendor/etc/partition_permission.sh:system/vendor/etc/partition_permission.sh \
    vendor/CUBOT/X18/vendor/etc/perfservapplist.txt:system/vendor/etc/perfservapplist.txt \
    vendor/CUBOT/X18/vendor/etc/perfservscntbl.txt:system/vendor/etc/perfservscntbl.txt \
    vendor/CUBOT/X18/vendor/etc/radvd/radvd.conf:system/vendor/etc/radvd/radvd.conf \
    vendor/CUBOT/X18/vendor/etc/recovery.fstab:system/vendor/etc/recovery.fstab \
    vendor/CUBOT/X18/vendor/etc/resmonwhitelist.txt:system/vendor/etc/resmonwhitelist.txt \
    vendor/CUBOT/X18/vendor/etc/security/cacerts_supl/594f1775.0:system/vendor/etc/security/cacerts_supl/594f1775.0 \
    vendor/CUBOT/X18/vendor/etc/security/cacerts_supl/7651b327.0:system/vendor/etc/security/cacerts_supl/7651b327.0 \
    vendor/CUBOT/X18/vendor/etc/security/cacerts_supl/848ea856.0:system/vendor/etc/security/cacerts_supl/848ea856.0 \
    vendor/CUBOT/X18/vendor/etc/security/cacerts_supl/c542733d.0:system/vendor/etc/security/cacerts_supl/c542733d.0 \
    vendor/CUBOT/X18/vendor/etc/security/cacerts_supl/f336e3d1.0:system/vendor/etc/security/cacerts_supl/f336e3d1.0 \
    vendor/CUBOT/X18/vendor/etc/slp_conf:system/vendor/etc/slp_conf \
    vendor/CUBOT/X18/vendor/etc/throttle.sh:system/vendor/etc/throttle.sh \
    vendor/CUBOT/X18/vendor/etc/virtual-spn-conf-by-efgid1.xml:system/vendor/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/CUBOT/X18/vendor/etc/virtual-spn-conf-by-efpnn.xml:system/vendor/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/CUBOT/X18/vendor/etc/virtual-spn-conf-by-efspn.xml:system/vendor/etc/virtual-spn-conf-by-efspn.xml \
    vendor/CUBOT/X18/vendor/etc/virtual-spn-conf-by-imsi.xml:system/vendor/etc/virtual-spn-conf-by-imsi.xml \
    vendor/CUBOT/X18/vendor/etc/voicecommand/training/ubmfile/128.dat:system/vendor/etc/voicecommand/training/ubmfile/128.dat \
    vendor/CUBOT/X18/vendor/etc/voicecommand/training/ubmfile/64.dat:system/vendor/etc/voicecommand/training/ubmfile/64.dat \
    vendor/CUBOT/X18/vendor/etc/voicecommand/training/ubmfile/antiCmds/Model1.bin:system/vendor/etc/voicecommand/training/ubmfile/antiCmds/Model1.bin \
    vendor/CUBOT/X18/vendor/etc/voicecommand/training/ubmfile/antiCmds/Model4.bin:system/vendor/etc/voicecommand/training/ubmfile/antiCmds/Model4.bin \
    vendor/CUBOT/X18/vendor/etc/voicecommand/training/ubmfile/antiCmds/c_e_dic.bin.f:system/vendor/etc/voicecommand/training/ubmfile/antiCmds/c_e_dic.bin.f \
    vendor/CUBOT/X18/vendor/etc/voicecommand/training/ubmfile/antiCmds/c_e_dic.bin.gen:system/vendor/etc/voicecommand/training/ubmfile/antiCmds/c_e_dic.bin.gen \
    vendor/CUBOT/X18/vendor/etc/voicecommand/training/ubmfile/antiCmds/c_e_dic.bin.l:system/vendor/etc/voicecommand/training/ubmfile/antiCmds/c_e_dic.bin.l \
    vendor/CUBOT/X18/vendor/etc/voicecommand/training/ubmfile/antiCmds/c_e_dic.bin.p:system/vendor/etc/voicecommand/training/ubmfile/antiCmds/c_e_dic.bin.p \
    vendor/CUBOT/X18/vendor/etc/voicecommand/training/ubmfile/antiCmds/c_e_dic.bin.t:system/vendor/etc/voicecommand/training/ubmfile/antiCmds/c_e_dic.bin.t \
    vendor/CUBOT/X18/vendor/etc/voicecommand/training/ubmfile/antiCmds/commandfilr3.dic:system/vendor/etc/voicecommand/training/ubmfile/antiCmds/commandfilr3.dic \
    vendor/CUBOT/X18/vendor/etc/voicecommand/training/ubmfile/ubmModel0.bin:system/vendor/etc/voicecommand/training/ubmfile/ubmModel0.bin \
    vendor/CUBOT/X18/vendor/etc/voicecommand/training/ubmfile/ubmModel1.bin:system/vendor/etc/voicecommand/training/ubmfile/ubmModel1.bin \
    vendor/CUBOT/X18/vendor/etc/voicecommand/training/ubmfile/ubmModel10.bin:system/vendor/etc/voicecommand/training/ubmfile/ubmModel10.bin \
    vendor/CUBOT/X18/vendor/etc/voicecommand/training/ubmfile/ubmModel2.bin:system/vendor/etc/voicecommand/training/ubmfile/ubmModel2.bin \
    vendor/CUBOT/X18/vendor/etc/voicecommand/training/ubmfile/ubmModel3.bin:system/vendor/etc/voicecommand/training/ubmfile/ubmModel3.bin \
    vendor/CUBOT/X18/vendor/etc/voicecommand/training/ubmfile/ubmModel4.bin:system/vendor/etc/voicecommand/training/ubmfile/ubmModel4.bin \
    vendor/CUBOT/X18/vendor/etc/wide-dhcpv6/dhcp6c.conf:system/vendor/etc/wide-dhcpv6/dhcp6c.conf \
    vendor/CUBOT/X18/vendor/etc/wide-dhcpv6/dhcp6c.script:system/vendor/etc/wide-dhcpv6/dhcp6c.script \
    vendor/CUBOT/X18/vendor/etc/wide-dhcpv6/dhcp6cDNS.conf:system/vendor/etc/wide-dhcpv6/dhcp6cDNS.conf \
    vendor/CUBOT/X18/vendor/etc/wide-dhcpv6/dhcp6cctlkey:system/vendor/etc/wide-dhcpv6/dhcp6cctlkey \
    vendor/CUBOT/X18/vendor/etc/wide-dhcpv6/dhcp6s.conf:system/vendor/etc/wide-dhcpv6/dhcp6s.conf \
    vendor/CUBOT/X18/vendor/firmware/ROMv2_lm_patch_1_0_hdr.bin:system/vendor/firmware/ROMv2_lm_patch_1_0_hdr.bin \
    vendor/CUBOT/X18/vendor/firmware/ROMv2_lm_patch_1_1_hdr.bin:system/vendor/firmware/ROMv2_lm_patch_1_1_hdr.bin \
    vendor/CUBOT/X18/vendor/firmware/WIFI_RAM_CODE_6735:system/vendor/firmware/WIFI_RAM_CODE_6735 \
    vendor/CUBOT/X18/vendor/firmware/WMT_SOC.cfg:system/vendor/firmware/WMT_SOC.cfg \
    vendor/CUBOT/X18/vendor/firmware/boot_3_3g_n.rom:system/vendor/firmware/boot_3_3g_n.rom \
    vendor/CUBOT/X18/vendor/firmware/catcher_filter_1_ltg_n.bin:system/vendor/firmware/catcher_filter_1_ltg_n.bin \
    vendor/CUBOT/X18/vendor/firmware/catcher_filter_1_lwg_n.bin:system/vendor/firmware/catcher_filter_1_lwg_n.bin \
    vendor/CUBOT/X18/vendor/firmware/catcher_filter_3_3g_n.bin:system/vendor/firmware/catcher_filter_3_3g_n.bin \
    vendor/CUBOT/X18/vendor/firmware/dsp_1_ltg_n.bin:system/vendor/firmware/dsp_1_ltg_n.bin \
    vendor/CUBOT/X18/vendor/firmware/dsp_1_lwg_n.bin:system/vendor/firmware/dsp_1_lwg_n.bin \
    vendor/CUBOT/X18/vendor/firmware/em_filter_1_ltg_n.bin:system/vendor/firmware/em_filter_1_ltg_n.bin \
    vendor/CUBOT/X18/vendor/firmware/em_filter_1_lwg_n.bin:system/vendor/firmware/em_filter_1_lwg_n.bin \
    vendor/CUBOT/X18/vendor/firmware/fm_cust.cfg:system/vendor/firmware/fm_cust.cfg \
    vendor/CUBOT/X18/vendor/firmware/fsm_cust_df_3_3g_n.img:system/vendor/firmware/fsm_cust_df_3_3g_n.img \
    vendor/CUBOT/X18/vendor/firmware/fsm_rf_df_3_3g_n.img:system/vendor/firmware/fsm_rf_df_3_3g_n.img \
    vendor/CUBOT/X18/vendor/firmware/fsm_rw_df_3_3g_n.img:system/vendor/firmware/fsm_rw_df_3_3g_n.img \
    vendor/CUBOT/X18/vendor/firmware/modem_1_ltg_n.img:system/vendor/firmware/modem_1_ltg_n.img \
    vendor/CUBOT/X18/vendor/firmware/modem_1_lwg_n.img:system/vendor/firmware/modem_1_lwg_n.img \
    vendor/CUBOT/X18/vendor/firmware/modem_3_3g_n.img:system/vendor/firmware/modem_3_3g_n.img \
    vendor/CUBOT/X18/vendor/firmware/mt6627_fm_v1_coeff.bin:system/vendor/firmware/mt6627_fm_v1_coeff.bin \
    vendor/CUBOT/X18/vendor/firmware/mt6627_fm_v1_patch.bin:system/vendor/firmware/mt6627_fm_v1_patch.bin \
    vendor/CUBOT/X18/vendor/lib/drm/libdrmctaplugin.so:system/vendor/lib/drm/libdrmctaplugin.so \
    vendor/CUBOT/X18/vendor/lib/drm/libdrmmtkplugin.so:system/vendor/lib/drm/libdrmmtkplugin.so \
    vendor/CUBOT/X18/vendor/lib/egl/egl.cfg:system/vendor/lib/egl/egl.cfg \
    vendor/CUBOT/X18/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/CUBOT/X18/vendor/lib/hw/audio.primary.mt6737t.so:system/vendor/lib/hw/audio.primary.mt6737t.so \
    vendor/CUBOT/X18/vendor/lib/hw/audio.r_submix.mt6737t.so:system/vendor/lib/hw/audio.r_submix.mt6737t.so \
    vendor/CUBOT/X18/vendor/lib/hw/audio.usb.mt6737t.so:system/vendor/lib/hw/audio.usb.mt6737t.so \
    vendor/CUBOT/X18/vendor/lib/hw/camera.mt6737t.so:system/vendor/lib/hw/camera.mt6737t.so \
    vendor/CUBOT/X18/vendor/lib/hw/gatekeeper.mt6737t.so:system/vendor/lib/hw/gatekeeper.mt6737t.so \
    vendor/CUBOT/X18/vendor/lib/hw/gps.mt6737t.so:system/vendor/lib/hw/gps.mt6737t.so \
    vendor/CUBOT/X18/vendor/lib/hw/gralloc.mt6737t.so:system/vendor/lib/hw/gralloc.mt6737t.so \
    vendor/CUBOT/X18/vendor/lib/hw/hwcomposer.mt6735.so:system/vendor/lib/hw/hwcomposer.mt6735.so \
    vendor/CUBOT/X18/vendor/lib/hw/keystore.mt6737t.so:system/vendor/lib/hw/keystore.mt6737t.so \
    vendor/CUBOT/X18/vendor/lib/hw/lights.mt6737t.so:system/vendor/lib/hw/lights.mt6737t.so \
    vendor/CUBOT/X18/vendor/lib/hw/memtrack.mt6737t.so:system/vendor/lib/hw/memtrack.mt6737t.so \
    vendor/CUBOT/X18/vendor/lib/hw/sensors.mt6737t.so:system/vendor/lib/hw/sensors.mt6737t.so \
    vendor/CUBOT/X18/vendor/lib/lib3a.so:system/vendor/lib/lib3a.so \
    vendor/CUBOT/X18/vendor/lib/lib3a_sample.so:system/vendor/lib/lib3a_sample.so \
    vendor/CUBOT/X18/vendor/lib/libBnMtkCodec.so:system/vendor/lib/libBnMtkCodec.so \
    vendor/CUBOT/X18/vendor/lib/libClearMotionFW.so:system/vendor/lib/libClearMotionFW.so \
    vendor/CUBOT/X18/vendor/lib/libHEVCdec_sa.ca7.android.so:system/vendor/lib/libHEVCdec_sa.ca7.android.so \
    vendor/CUBOT/X18/vendor/lib/libJpgDecPipe.so:system/vendor/lib/libJpgDecPipe.so \
    vendor/CUBOT/X18/vendor/lib/libJpgEncPipe.so:system/vendor/lib/libJpgEncPipe.so \
    vendor/CUBOT/X18/vendor/lib/libMiraVision_jni.so:system/vendor/lib/libMiraVision_jni.so \
    vendor/CUBOT/X18/vendor/lib/libMtkOmxAdpcmDec.so:system/vendor/lib/libMtkOmxAdpcmDec.so \
    vendor/CUBOT/X18/vendor/lib/libMtkOmxAdpcmEnc.so:system/vendor/lib/libMtkOmxAdpcmEnc.so \
    vendor/CUBOT/X18/vendor/lib/libMtkOmxApeDec.so:system/vendor/lib/libMtkOmxApeDec.so \
    vendor/CUBOT/X18/vendor/lib/libMtkOmxCore.so:system/vendor/lib/libMtkOmxCore.so \
    vendor/CUBOT/X18/vendor/lib/libMtkOmxFlacDec.so:system/vendor/lib/libMtkOmxFlacDec.so \
    vendor/CUBOT/X18/vendor/lib/libMtkOmxG711Dec.so:system/vendor/lib/libMtkOmxG711Dec.so \
    vendor/CUBOT/X18/vendor/lib/libMtkOmxGsmDec.so:system/vendor/lib/libMtkOmxGsmDec.so \
    vendor/CUBOT/X18/vendor/lib/libMtkOmxMp3Dec.so:system/vendor/lib/libMtkOmxMp3Dec.so \
    vendor/CUBOT/X18/vendor/lib/libMtkOmxRawDec.so:system/vendor/lib/libMtkOmxRawDec.so \
    vendor/CUBOT/X18/vendor/lib/libMtkOmxVdecEx.so:system/vendor/lib/libMtkOmxVdecEx.so \
    vendor/CUBOT/X18/vendor/lib/libMtkOmxVenc.so:system/vendor/lib/libMtkOmxVenc.so \
    vendor/CUBOT/X18/vendor/lib/libMtkOmxVorbisEnc.so:system/vendor/lib/libMtkOmxVorbisEnc.so \
    vendor/CUBOT/X18/vendor/lib/libMtkVideoSpeedEffect.so:system/vendor/lib/libMtkVideoSpeedEffect.so \
    vendor/CUBOT/X18/vendor/lib/libOpenCLIcd.so:system/vendor/lib/libOpenCLIcd.so \
    vendor/CUBOT/X18/vendor/lib/libPQDCjni.so:system/vendor/lib/libPQDCjni.so \
    vendor/CUBOT/X18/vendor/lib/libPQjni.so:system/vendor/lib/libPQjni.so \
    vendor/CUBOT/X18/vendor/lib/libRSDriver_mtk.so:system/vendor/lib/libRSDriver_mtk.so \
    vendor/CUBOT/X18/vendor/lib/libSonyIMX230PdafLibrary.so:system/vendor/lib/libSonyIMX230PdafLibrary.so \
    vendor/CUBOT/X18/vendor/lib/libSwJpgCodec.so:system/vendor/lib/libSwJpgCodec.so \
    vendor/CUBOT/X18/vendor/lib/libaal.so:system/vendor/lib/libaal.so \
    vendor/CUBOT/X18/vendor/lib/libaal_cust.so:system/vendor/lib/libaal_cust.so \
    vendor/CUBOT/X18/vendor/lib/libacdk.so:system/vendor/lib/libacdk.so \
    vendor/CUBOT/X18/vendor/lib/libaed.so:system/vendor/lib/libaed.so \
    vendor/CUBOT/X18/vendor/lib/libamr_wrap.so:system/vendor/lib/libamr_wrap.so \
    vendor/CUBOT/X18/vendor/lib/libamrvt.so:system/vendor/lib/libamrvt.so \
    vendor/CUBOT/X18/vendor/lib/libatciserv_jni.so:system/vendor/lib/libatciserv_jni.so \
    vendor/CUBOT/X18/vendor/lib/libatvctrlservice.so:system/vendor/lib/libatvctrlservice.so \
    vendor/CUBOT/X18/vendor/lib/libaudio_param_parser.so:system/vendor/lib/libaudio_param_parser.so \
    vendor/CUBOT/X18/vendor/lib/libaudiocompensationfilter.so:system/vendor/lib/libaudiocompensationfilter.so \
    vendor/CUBOT/X18/vendor/lib/libaudiocomponentengine.so:system/vendor/lib/libaudiocomponentengine.so \
    vendor/CUBOT/X18/vendor/lib/libaudiocustparam.so:system/vendor/lib/libaudiocustparam.so \
    vendor/CUBOT/X18/vendor/lib/libaudiodcrflt.so:system/vendor/lib/libaudiodcrflt.so \
    vendor/CUBOT/X18/vendor/lib/libaudiomtkdcremoval.so:system/vendor/lib/libaudiomtkdcremoval.so \
    vendor/CUBOT/X18/vendor/lib/libaudiosetting.so:system/vendor/lib/libaudiosetting.so \
    vendor/CUBOT/X18/vendor/lib/libaudiotoolkit.so:system/vendor/lib/libaudiotoolkit.so \
    vendor/CUBOT/X18/vendor/lib/libawb_wrap.so:system/vendor/lib/libawb_wrap.so \
    vendor/CUBOT/X18/vendor/lib/libbessound_hd_mtk.so:system/vendor/lib/libbessound_hd_mtk.so \
    vendor/CUBOT/X18/vendor/lib/libblisrc.so:system/vendor/lib/libblisrc.so \
    vendor/CUBOT/X18/vendor/lib/libblisrc32.so:system/vendor/lib/libblisrc32.so \
    vendor/CUBOT/X18/vendor/lib/libbluetooth_hw_test.so:system/vendor/lib/libbluetooth_hw_test.so \
    vendor/CUBOT/X18/vendor/lib/libbluetooth_mtk.so:system/vendor/lib/libbluetooth_mtk.so \
    vendor/CUBOT/X18/vendor/lib/libbluetooth_mtk_pure.so:system/vendor/lib/libbluetooth_mtk_pure.so \
    vendor/CUBOT/X18/vendor/lib/libbluetooth_relayer.so:system/vendor/lib/libbluetooth_relayer.so \
    vendor/CUBOT/X18/vendor/lib/libbluetoothem_mtk.so:system/vendor/lib/libbluetoothem_mtk.so \
    vendor/CUBOT/X18/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    vendor/CUBOT/X18/vendor/lib/libbwc.so:system/vendor/lib/libbwc.so \
    vendor/CUBOT/X18/vendor/lib/libc2kril.so:system/vendor/lib/libc2kril.so \
    vendor/CUBOT/X18/vendor/lib/libc2kutils.so:system/vendor/lib/libc2kutils.so \
    vendor/CUBOT/X18/vendor/lib/libcam.camadapter.so:system/vendor/lib/libcam.camadapter.so \
    vendor/CUBOT/X18/vendor/lib/libcam.camnode.so:system/vendor/lib/libcam.camnode.so \
    vendor/CUBOT/X18/vendor/lib/libcam.camshot.so:system/vendor/lib/libcam.camshot.so \
    vendor/CUBOT/X18/vendor/lib/libcam.client.so:system/vendor/lib/libcam.client.so \
    vendor/CUBOT/X18/vendor/lib/libcam.device1.so:system/vendor/lib/libcam.device1.so \
    vendor/CUBOT/X18/vendor/lib/libcam.device3.so:system/vendor/lib/libcam.device3.so \
    vendor/CUBOT/X18/vendor/lib/libcam.exif.so:system/vendor/lib/libcam.exif.so \
    vendor/CUBOT/X18/vendor/lib/libcam.exif.v3.so:system/vendor/lib/libcam.exif.v3.so \
    vendor/CUBOT/X18/vendor/lib/libcam.hal3a.v3.dng.so:system/vendor/lib/libcam.hal3a.v3.dng.so \
    vendor/CUBOT/X18/vendor/lib/libcam.hal3a.v3.so:system/vendor/lib/libcam.hal3a.v3.so \
    vendor/CUBOT/X18/vendor/lib/libcam.halsensor.so:system/vendor/lib/libcam.halsensor.so \
    vendor/CUBOT/X18/vendor/lib/libcam.iopipe.so:system/vendor/lib/libcam.iopipe.so \
    vendor/CUBOT/X18/vendor/lib/libcam.jni.lomohaljni.so:system/vendor/lib/libcam.jni.lomohaljni.so \
    vendor/CUBOT/X18/vendor/lib/libcam.metadata.so:system/vendor/lib/libcam.metadata.so \
    vendor/CUBOT/X18/vendor/lib/libcam.metadataprovider.so:system/vendor/lib/libcam.metadataprovider.so \
    vendor/CUBOT/X18/vendor/lib/libcam.paramsmgr.so:system/vendor/lib/libcam.paramsmgr.so \
    vendor/CUBOT/X18/vendor/lib/libcam.utils.cpuctrl.so:system/vendor/lib/libcam.utils.cpuctrl.so \
    vendor/CUBOT/X18/vendor/lib/libcam.utils.sensorlistener.so:system/vendor/lib/libcam.utils.sensorlistener.so \
    vendor/CUBOT/X18/vendor/lib/libcam.utils.so:system/vendor/lib/libcam.utils.so \
    vendor/CUBOT/X18/vendor/lib/libcam1_utils.so:system/vendor/lib/libcam1_utils.so \
    vendor/CUBOT/X18/vendor/lib/libcam3_app.so:system/vendor/lib/libcam3_app.so \
    vendor/CUBOT/X18/vendor/lib/libcam3_hwnode.so:system/vendor/lib/libcam3_hwnode.so \
    vendor/CUBOT/X18/vendor/lib/libcam3_hwpipeline.so:system/vendor/lib/libcam3_hwpipeline.so \
    vendor/CUBOT/X18/vendor/lib/libcam3_pipeline.so:system/vendor/lib/libcam3_pipeline.so \
    vendor/CUBOT/X18/vendor/lib/libcam3_utils.so:system/vendor/lib/libcam3_utils.so \
    vendor/CUBOT/X18/vendor/lib/libcam_hwutils.so:system/vendor/lib/libcam_hwutils.so \
    vendor/CUBOT/X18/vendor/lib/libcam_mmp.so:system/vendor/lib/libcam_mmp.so \
    vendor/CUBOT/X18/vendor/lib/libcam_platform.so:system/vendor/lib/libcam_platform.so \
    vendor/CUBOT/X18/vendor/lib/libcam_utils.so:system/vendor/lib/libcam_utils.so \
    vendor/CUBOT/X18/vendor/lib/libcamalgo.so:system/vendor/lib/libcamalgo.so \
    vendor/CUBOT/X18/vendor/lib/libcamdrv.so:system/vendor/lib/libcamdrv.so \
    vendor/CUBOT/X18/vendor/lib/libcameracustom.so:system/vendor/lib/libcameracustom.so \
    vendor/CUBOT/X18/vendor/lib/libccci_util.so:system/vendor/lib/libccci_util.so \
    vendor/CUBOT/X18/vendor/lib/libcharon.so:system/vendor/lib/libcharon.so \
    vendor/CUBOT/X18/vendor/lib/libcomutils.so:system/vendor/lib/libcomutils.so \
    vendor/CUBOT/X18/vendor/lib/libcrypto-ss.so:system/vendor/lib/libcrypto-ss.so \
    vendor/CUBOT/X18/vendor/lib/libcurl-ss.so:system/vendor/lib/libcurl-ss.so \
    vendor/CUBOT/X18/vendor/lib/libcustom_jni.so:system/vendor/lib/libcustom_jni.so \
    vendor/CUBOT/X18/vendor/lib/libcustom_nvram.so:system/vendor/lib/libcustom_nvram.so \
    vendor/CUBOT/X18/vendor/lib/libcustom_prop.so:system/vendor/lib/libcustom_prop.so \
    vendor/CUBOT/X18/vendor/lib/libcvsd_mtk.so:system/vendor/lib/libcvsd_mtk.so \
    vendor/CUBOT/X18/vendor/lib/libdirect-coredump.so:system/vendor/lib/libdirect-coredump.so \
    vendor/CUBOT/X18/vendor/lib/libdngop.so:system/vendor/lib/libdngop.so \
    vendor/CUBOT/X18/vendor/lib/libdpframework.so:system/vendor/lib/libdpframework.so \
    vendor/CUBOT/X18/vendor/lib/libdrmmtkutil.so:system/vendor/lib/libdrmmtkutil.so \
    vendor/CUBOT/X18/vendor/lib/libdrmmtkwhitelist.so:system/vendor/lib/libdrmmtkwhitelist.so \
    vendor/CUBOT/X18/vendor/lib/libeffect.facebeautypp.so:system/vendor/lib/libeffect.facebeautypp.so \
    vendor/CUBOT/X18/vendor/lib/libeffecthal.JPG.so:system/vendor/lib/libeffecthal.JPG.so \
    vendor/CUBOT/X18/vendor/lib/libeffecthal.base.so:system/vendor/lib/libeffecthal.base.so \
    vendor/CUBOT/X18/vendor/lib/libem_audio_jni.so:system/vendor/lib/libem_audio_jni.so \
    vendor/CUBOT/X18/vendor/lib/libem_bt_jni.so:system/vendor/lib/libem_bt_jni.so \
    vendor/CUBOT/X18/vendor/lib/libem_gpio_jni.so:system/vendor/lib/libem_gpio_jni.so \
    vendor/CUBOT/X18/vendor/lib/libem_lte_jni.so:system/vendor/lib/libem_lte_jni.so \
    vendor/CUBOT/X18/vendor/lib/libem_modem_jni.so:system/vendor/lib/libem_modem_jni.so \
    vendor/CUBOT/X18/vendor/lib/libem_sensor_jni.so:system/vendor/lib/libem_sensor_jni.so \
    vendor/CUBOT/X18/vendor/lib/libem_support_jni.so:system/vendor/lib/libem_support_jni.so \
    vendor/CUBOT/X18/vendor/lib/libem_usb_jni.so:system/vendor/lib/libem_usb_jni.so \
    vendor/CUBOT/X18/vendor/lib/libem_wifi_jni.so:system/vendor/lib/libem_wifi_jni.so \
    vendor/CUBOT/X18/vendor/lib/libfeatureio.cfb.so:system/vendor/lib/libfeatureio.cfb.so \
    vendor/CUBOT/X18/vendor/lib/libfeatureio.featurefactory.so:system/vendor/lib/libfeatureio.featurefactory.so \
    vendor/CUBOT/X18/vendor/lib/libfeatureio.jpg.so:system/vendor/lib/libfeatureio.jpg.so \
    vendor/CUBOT/X18/vendor/lib/libfeatureio.so:system/vendor/lib/libfeatureio.so \
    vendor/CUBOT/X18/vendor/lib/libfeatureiodrv.so:system/vendor/lib/libfeatureiodrv.so \
    vendor/CUBOT/X18/vendor/lib/libfgauge.so:system/vendor/lib/libfgauge.so \
    vendor/CUBOT/X18/vendor/lib/libfile_op.so:system/vendor/lib/libfile_op.so \
    vendor/CUBOT/X18/vendor/lib/libfmcust.so:system/vendor/lib/libfmcust.so \
    vendor/CUBOT/X18/vendor/lib/libfmjni.so:system/vendor/lib/libfmjni.so \
    vendor/CUBOT/X18/vendor/lib/libfposervice.so:system/vendor/lib/libfposervice.so \
    vendor/CUBOT/X18/vendor/lib/libgas.so:system/vendor/lib/libgas.so \
    vendor/CUBOT/X18/vendor/lib/libged.so:system/vendor/lib/libged.so \
    vendor/CUBOT/X18/vendor/lib/libgpu_aux.so:system/vendor/lib/libgpu_aux.so \
    vendor/CUBOT/X18/vendor/lib/libgralloc_extra.so:system/vendor/lib/libgralloc_extra.so \
    vendor/CUBOT/X18/vendor/lib/libgui_ext.so:system/vendor/lib/libgui_ext.so \
    vendor/CUBOT/X18/vendor/lib/libh264enc_sa.ca7.so:system/vendor/lib/libh264enc_sa.ca7.so \
    vendor/CUBOT/X18/vendor/lib/libh264enc_sb.ca7.so:system/vendor/lib/libh264enc_sb.ca7.so \
    vendor/CUBOT/X18/vendor/lib/libhwm.so:system/vendor/lib/libhwm.so \
    vendor/CUBOT/X18/vendor/lib/libhydra.so:system/vendor/lib/libhydra.so \
    vendor/CUBOT/X18/vendor/lib/libimageio.so:system/vendor/lib/libimageio.so \
    vendor/CUBOT/X18/vendor/lib/libimageio_plat_drv.so:system/vendor/lib/libimageio_plat_drv.so \
    vendor/CUBOT/X18/vendor/lib/libimsma.so:system/vendor/lib/libimsma.so \
    vendor/CUBOT/X18/vendor/lib/libimsma_rtp.so:system/vendor/lib/libimsma_rtp.so \
    vendor/CUBOT/X18/vendor/lib/libimsma_socketwrapper.so:system/vendor/lib/libimsma_socketwrapper.so \
    vendor/CUBOT/X18/vendor/lib/libion_mtk.so:system/vendor/lib/libion_mtk.so \
    vendor/CUBOT/X18/vendor/lib/libipsec_ims_shr.so:system/vendor/lib/libipsec_ims_shr.so \
    vendor/CUBOT/X18/vendor/lib/libjni_jpegdecoder.so:system/vendor/lib/libjni_jpegdecoder.so \
    vendor/CUBOT/X18/vendor/lib/libjni_lomoeffect.so:system/vendor/lib/libjni_lomoeffect.so \
    vendor/CUBOT/X18/vendor/lib/libjni_pq.so:system/vendor/lib/libjni_pq.so \
    vendor/CUBOT/X18/vendor/lib/liblic_divx.so:system/vendor/lib/liblic_divx.so \
    vendor/CUBOT/X18/vendor/lib/liblic_s263.so:system/vendor/lib/liblic_s263.so \
    vendor/CUBOT/X18/vendor/lib/liblocSDK6c.so:system/vendor/lib/liblocSDK6c.so \
    vendor/CUBOT/X18/vendor/lib/libm4u.so:system/vendor/lib/libm4u.so \
    vendor/CUBOT/X18/vendor/lib/libmal.so:system/vendor/lib/libmal.so \
    vendor/CUBOT/X18/vendor/lib/libmal_datamngr.so:system/vendor/lib/libmal_datamngr.so \
    vendor/CUBOT/X18/vendor/lib/libmal_epdga.so:system/vendor/lib/libmal_epdga.so \
    vendor/CUBOT/X18/vendor/lib/libmal_imsmngr.so:system/vendor/lib/libmal_imsmngr.so \
    vendor/CUBOT/X18/vendor/lib/libmal_mdmngr.so:system/vendor/lib/libmal_mdmngr.so \
    vendor/CUBOT/X18/vendor/lib/libmal_nwmngr.so:system/vendor/lib/libmal_nwmngr.so \
    vendor/CUBOT/X18/vendor/lib/libmal_rds.so:system/vendor/lib/libmal_rds.so \
    vendor/CUBOT/X18/vendor/lib/libmal_rilproxy.so:system/vendor/lib/libmal_rilproxy.so \
    vendor/CUBOT/X18/vendor/lib/libmal_simmngr.so:system/vendor/lib/libmal_simmngr.so \
    vendor/CUBOT/X18/vendor/lib/libmatv_cust.so:system/vendor/lib/libmatv_cust.so \
    vendor/CUBOT/X18/vendor/lib/libmdfx.so:system/vendor/lib/libmdfx.so \
    vendor/CUBOT/X18/vendor/lib/libmdloggerrecycle.so:system/vendor/lib/libmdloggerrecycle.so \
    vendor/CUBOT/X18/vendor/lib/libmemoryDumpEncoder.so:system/vendor/lib/libmemoryDumpEncoder.so \
    vendor/CUBOT/X18/vendor/lib/libmemorydumper.so:system/vendor/lib/libmemorydumper.so \
    vendor/CUBOT/X18/vendor/lib/libmhalImageCodec.so:system/vendor/lib/libmhalImageCodec.so \
    vendor/CUBOT/X18/vendor/lib/libminiui.so:system/vendor/lib/libminiui.so \
    vendor/CUBOT/X18/vendor/lib/libmjcFakeEngine.so:system/vendor/lib/libmjcFakeEngine.so \
    vendor/CUBOT/X18/vendor/lib/libmmprofile.so:system/vendor/lib/libmmprofile.so \
    vendor/CUBOT/X18/vendor/lib/libmmprofile_jni.so:system/vendor/lib/libmmprofile_jni.so \
    vendor/CUBOT/X18/vendor/lib/libmmsdkservice.so:system/vendor/lib/libmmsdkservice.so \
    vendor/CUBOT/X18/vendor/lib/libmnl.so:system/vendor/lib/libmnl.so \
    vendor/CUBOT/X18/vendor/lib/libmp4enc_sa.ca7.so:system/vendor/lib/libmp4enc_sa.ca7.so \
    vendor/CUBOT/X18/vendor/lib/libmp4enc_xa.ca7.so:system/vendor/lib/libmp4enc_xa.ca7.so \
    vendor/CUBOT/X18/vendor/lib/libmrdump.so:system/vendor/lib/libmrdump.so \
    vendor/CUBOT/X18/vendor/lib/libmsbc_mtk.so:system/vendor/lib/libmsbc_mtk.so \
    vendor/CUBOT/X18/vendor/lib/libmtcloader.so:system/vendor/lib/libmtcloader.so \
    vendor/CUBOT/X18/vendor/lib/libmtk_drvb.so:system/vendor/lib/libmtk_drvb.so \
    vendor/CUBOT/X18/vendor/lib/libmtk_mmutils.so:system/vendor/lib/libmtk_mmutils.so \
    vendor/CUBOT/X18/vendor/lib/libmtk_vt_service.so:system/vendor/lib/libmtk_vt_service.so \
    vendor/CUBOT/X18/vendor/lib/libmtk_vt_swip.so:system/vendor/lib/libmtk_vt_swip.so \
    vendor/CUBOT/X18/vendor/lib/libmtk_vt_utils.so:system/vendor/lib/libmtk_vt_utils.so \
    vendor/CUBOT/X18/vendor/lib/libmtk_vt_wrapper.so:system/vendor/lib/libmtk_vt_wrapper.so \
    vendor/CUBOT/X18/vendor/lib/libmtkcam_fwkutils.so:system/vendor/lib/libmtkcam_fwkutils.so \
    vendor/CUBOT/X18/vendor/lib/libmtkjpeg.so:system/vendor/lib/libmtkjpeg.so \
    vendor/CUBOT/X18/vendor/lib/libmtklimiter.so:system/vendor/lib/libmtklimiter.so \
    vendor/CUBOT/X18/vendor/lib/libmtkplayer.so:system/vendor/lib/libmtkplayer.so \
    vendor/CUBOT/X18/vendor/lib/libmtkshifter.so:system/vendor/lib/libmtkshifter.so \
    vendor/CUBOT/X18/vendor/lib/libn3d3a.so:system/vendor/lib/libn3d3a.so \
    vendor/CUBOT/X18/vendor/lib/libnativecheck-jni.so:system/vendor/lib/libnativecheck-jni.so \
    vendor/CUBOT/X18/vendor/lib/libnetworklocation.so:system/vendor/lib/libnetworklocation.so \
    vendor/CUBOT/X18/vendor/lib/libnvram.so:system/vendor/lib/libnvram.so \
    vendor/CUBOT/X18/vendor/lib/libnvram_daemon_callback.so:system/vendor/lib/libnvram_daemon_callback.so \
    vendor/CUBOT/X18/vendor/lib/libnvram_platform.so:system/vendor/lib/libnvram_platform.so \
    vendor/CUBOT/X18/vendor/lib/libnvram_sec.so:system/vendor/lib/libnvram_sec.so \
    vendor/CUBOT/X18/vendor/lib/libnvramagentclient.so:system/vendor/lib/libnvramagentclient.so \
    vendor/CUBOT/X18/vendor/lib/libperfservice.so:system/vendor/lib/libperfservice.so \
    vendor/CUBOT/X18/vendor/lib/libperfservicenative.so:system/vendor/lib/libperfservicenative.so \
    vendor/CUBOT/X18/vendor/lib/libpq_cust.so:system/vendor/lib/libpq_cust.so \
    vendor/CUBOT/X18/vendor/lib/libpq_prot.so:system/vendor/lib/libpq_prot.so \
    vendor/CUBOT/X18/vendor/lib/libpqservice.so:system/vendor/lib/libpqservice.so \
    vendor/CUBOT/X18/vendor/lib/libprogrambinary.so:system/vendor/lib/libprogrambinary.so \
    vendor/CUBOT/X18/vendor/lib/libratconfig.so:system/vendor/lib/libratconfig.so \
    vendor/CUBOT/X18/vendor/lib/librilmtk.so:system/vendor/lib/librilmtk.so \
    vendor/CUBOT/X18/vendor/lib/librilmtkmd2.so:system/vendor/lib/librilmtkmd2.so \
    vendor/CUBOT/X18/vendor/lib/librilproxy.so:system/vendor/lib/librilproxy.so \
    vendor/CUBOT/X18/vendor/lib/librilproxyutils.so:system/vendor/lib/librilproxyutils.so \
    vendor/CUBOT/X18/vendor/lib/librpc.so:system/vendor/lib/librpc.so \
    vendor/CUBOT/X18/vendor/lib/librpcril.so:system/vendor/lib/librpcril.so \
    vendor/CUBOT/X18/vendor/lib/librrc.so:system/vendor/lib/librrc.so \
    vendor/CUBOT/X18/vendor/lib/libshowlogo.so:system/vendor/lib/libshowlogo.so \
    vendor/CUBOT/X18/vendor/lib/libsimaka.so:system/vendor/lib/libsimaka.so \
    vendor/CUBOT/X18/vendor/lib/libsink.so:system/vendor/lib/libsink.so \
    vendor/CUBOT/X18/vendor/lib/libsource.so:system/vendor/lib/libsource.so \
    vendor/CUBOT/X18/vendor/lib/libspeech_enh_lib.so:system/vendor/lib/libspeech_enh_lib.so \
    vendor/CUBOT/X18/vendor/lib/libssl-ss.so:system/vendor/lib/libssl-ss.so \
    vendor/CUBOT/X18/vendor/lib/libstagefrighthw.so:system/vendor/lib/libstagefrighthw.so \
    vendor/CUBOT/X18/vendor/lib/libstorage_otp.so:system/vendor/lib/libstorage_otp.so \
    vendor/CUBOT/X18/vendor/lib/libstrongswan.so:system/vendor/lib/libstrongswan.so \
    vendor/CUBOT/X18/vendor/lib/libsysenv.so:system/vendor/lib/libsysenv.so \
    vendor/CUBOT/X18/vendor/lib/libterservice.so:system/vendor/lib/libterservice.so \
    vendor/CUBOT/X18/vendor/lib/libtimestretch.so:system/vendor/lib/libtimestretch.so \
    vendor/CUBOT/X18/vendor/lib/libtouchfilter.so:system/vendor/lib/libtouchfilter.so \
    vendor/CUBOT/X18/vendor/lib/libudf.so:system/vendor/lib/libudf.so \
    vendor/CUBOT/X18/vendor/lib/libui_ext.so:system/vendor/lib/libui_ext.so \
    vendor/CUBOT/X18/vendor/lib/libuvtswenc_sa.ca7.android.so:system/vendor/lib/libuvtswenc_sa.ca7.android.so \
    vendor/CUBOT/X18/vendor/lib/libvc1dec_sa.ca7.so:system/vendor/lib/libvc1dec_sa.ca7.so \
    vendor/CUBOT/X18/vendor/lib/libvcodec_cap.so:system/vendor/lib/libvcodec_cap.so \
    vendor/CUBOT/X18/vendor/lib/libvcodec_oal.so:system/vendor/lib/libvcodec_oal.so \
    vendor/CUBOT/X18/vendor/lib/libvcodec_utility.so:system/vendor/lib/libvcodec_utility.so \
    vendor/CUBOT/X18/vendor/lib/libvcodecdrv.so:system/vendor/lib/libvcodecdrv.so \
    vendor/CUBOT/X18/vendor/lib/libviagpsrpc.so:system/vendor/lib/libviagpsrpc.so \
    vendor/CUBOT/X18/vendor/lib/libviatelecom-withuim-ril.so:system/vendor/lib/libviatelecom-withuim-ril.so \
    vendor/CUBOT/X18/vendor/lib/libvoicerecognition.so:system/vendor/lib/libvoicerecognition.so \
    vendor/CUBOT/X18/vendor/lib/libvoicerecognition_jni.so:system/vendor/lib/libvoicerecognition_jni.so \
    vendor/CUBOT/X18/vendor/lib/libvp8dec_sa.ca7.so:system/vendor/lib/libvp8dec_sa.ca7.so \
    vendor/CUBOT/X18/vendor/lib/libvp8enc_sa.ca7.so:system/vendor/lib/libvp8enc_sa.ca7.so \
    vendor/CUBOT/X18/vendor/lib/libvp9dec_sa.ca7.so:system/vendor/lib/libvp9dec_sa.ca7.so \
    vendor/CUBOT/X18/vendor/lib/libvt_avsync.so:system/vendor/lib/libvt_avsync.so \
    vendor/CUBOT/X18/vendor/lib/libvt_custom.so:system/vendor/lib/libvt_custom.so \
    vendor/CUBOT/X18/vendor/lib/libvt_socketbind.so:system/vendor/lib/libvt_socketbind.so \
    vendor/CUBOT/X18/vendor/lib/libvtmal.so:system/vendor/lib/libvtmal.so \
    vendor/CUBOT/X18/vendor/lib/libwapi.so:system/vendor/lib/libwapi.so \
    vendor/CUBOT/X18/vendor/lib/libwfo_jni.so:system/vendor/lib/libwfo_jni.so \
    vendor/CUBOT/X18/vendor/lib/libwifitest.so:system/vendor/lib/libwifitest.so \
    vendor/CUBOT/X18/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/CUBOT/X18/vendor/lib/mediadrm/libmockdrmcryptoplugin.so:system/vendor/lib/mediadrm/libmockdrmcryptoplugin.so \
    vendor/CUBOT/X18/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/CUBOT/X18/vendor/lib/mtk-ril.so:system/vendor/lib/mtk-ril.so \
    vendor/CUBOT/X18/vendor/lib/mtk-rilmd2.so:system/vendor/lib/mtk-rilmd2.so \
    vendor/CUBOT/X18/vendor/lib/mtk-rilproxy.so:system/vendor/lib/mtk-rilproxy.so \
    vendor/CUBOT/X18/vendor/lib/volte_imsm.so:system/vendor/lib/volte_imsm.so
